## 数组转置和轴对换

In [3]:
import numpy as np
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr = np.random.randn(6,3)

In [6]:
#利用np.dot计算矩阵的内积
np.dot(arr.T,arr)

array([[ 1.88280449, -0.59108282,  0.01908372],
       [-0.59108282,  5.82607106, -3.18290971],
       [ 0.01908372, -3.18290971,  5.21425339]])

In [ ]:
#高维数组的转置transpose和swapaxs