## 通用函数：快速的元素级数组函数

In [1]:
#通用函数（ufunc）
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [7]:
x = np.random.randn(8)
x

array([-0.16078745,  0.41546654,  0.41191867, -0.17915509,  1.00408716,
       -1.09811799,  0.23341391,  0.86908284])

In [8]:
y = np.random.randn(8)
y

array([-0.35429015,  0.43237739,  1.4086513 , -0.8505909 ,  2.5046506 ,
       -0.12822983,  0.93936179, -0.48661299])

In [10]:
np.max(x)

1.0040871613041624

In [11]:
#max只能处理一个数组，maximum可以处理两个数组
np.maximum(x,y)

array([-0.16078745,  0.43237739,  1.4086513 , -0.17915509,  2.5046506 ,
       -0.12822983,  0.93936179,  0.86908284])

In [12]:
z = np.random.randn(8)*5
z

array([ 9.32007285, -8.69118054,  2.10550107, -0.16426047,  5.44602398,
        3.3658145 , -8.89844478,  0.03180466])

In [17]:
#modf剥离整数和小数部分
xiaoshu = np.modf(z)[0]
xiaoshu

(array([ 0.32007285, -0.69118054,  0.10550107, -0.16426047,  0.44602398,
         0.3658145 , -0.89844478,  0.03180466]),
 array([ 9., -8.,  2., -0.,  5.,  3., -8.,  0.]))

In [18]:
zhenshu = np.modf(z)[1]
zhenshu

array([ 9., -8.,  2., -0.,  5.,  3., -8.,  0.])

In [19]:
m = np.arange(10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#求模计算
np.mod(m,3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [24]:
?np