# 标准化

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [3]:
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

### 查看均值方差

In [4]:
X_scaled.mean(axis=0)

array([ 0.,  0.,  0.])

In [ ]:
X_scaled.std(axis=0)

In [6]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [7]:
scaler.mean_

array([ 1.        ,  0.        ,  0.33333333])

In [8]:
scaler.scale_

array([ 0.81649658,  0.81649658,  1.24721913])

In [9]:
scaler.transform(X_train) 

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [10]:
X_test = [[-1., 1., 0.]]

In [11]:
scaler.transform(X_test) 

array([[-2.44948974,  1.22474487, -0.26726124]])

In [12]:
X_test = [[1, 1., 1]]

In [15]:
?scaler.transform(X_test)